### ISSUE TITLE
differences with `github.com/pgx-contrib/pgxotel`?

### ISSUE THREAD

**Issue by StevenACoffman** [exaring/otelpgx#38]
Hi, I'm just curious about the differences between this and `github.com/pgx-contrib/pgxotel`?

I currently use pgxpool, so I can swap between them fairly easily.

**Comment by obitech** [comment]
I'm not familiar with `github.com/pgx-contrib/pgxotel` but it looks like the lib is doing the same at the core, as both otelpgx and pgxotel implement the necessary pgx Tracer interfaces. Apart from that I'd say that otelpgx offers a couple more options to configure the lib right now, but this is really just sugar on top. You'll be able to trace your pgx just fine with both of them 😊

**Comment by StevenACoffman** [comment]
There are a handful of libraries that do the same thing, but they are not as widely used as this exaring/otelpgx one:
https://pkg.go.dev/github.com/exaring/otelpgx
https://pkg.go.dev/github.com/pgx-contrib/pgxotel
https://pkg.go.dev/github.com/quantumsheep/otelpgxpool
